// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed/seed.ts"
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Neon can't create/drop shadow databases on the fly, so point Prisma at a
    // dedicated one instead of letting it provision a throwaway per run.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
